- Submit/kukim/Stack_Queue/기능개발/solution.py
브랜치 & PR 테스트입니다.
기능개발 문제 풀었습니다.
> [Stack_queue] - 기능개발

- Submit/morgan-ha/Stack_Queue/주식가격/solution.py
- 1번은 제가 푼 풀이입니다.
- 2, 3번은 stack을 이용한 풀이입니다.
> [톰하토] 1주차 주식문제 풀이

- Submit/kukim/Stack_Queue/다리를건너는트럭/solution.py
- Submit/kukim/Stack_Queue/주식가격/solution.py
- Submit/kukim/Stack_Queue/프린터/solution.py
> Stack_queue 다리를건너는트럭, 주식가격, 프린터 문제 풀이

- Submit/kukim/Stack_Queue/다리를건너는트럭/solution.py
- Submit/kukim/Stack_Queue/주식가격/solution.py
- Submit/kukim/Stack_Queue/프린터/solution.py
프로그래머스의 Stack & Queue 문제 풀이 완료
> [kukim] - Stack_queue : 다리를건너는트럭, 주식가격, 프린터 문제 풀이

- Submit/dave/BruteForce/README.md
- Submit/dave/Greedy/README.md
- Submit/dave/Hash/README.md
- Submit/dave/Heap/README.md
- Submit/dave/Sorting/README.md
- Submit/dave/Stack_Queue/README.md
- Submit/dave/Stack_Queue/프린터/solution.py
> [Dave] 1주차 프린터 풀이 완료

- Submit/dave/Hash/베스트앨범/solution.py
- Submit/dave/Hash/보석과돌/solution.py
- Submit/dave/Hash/상위K빈도요소/solution.py
- Submit/dave/Hash/위장/solution.py
- Submit/dave/Hash/중복문자없는가장긴문자열/solution.py
- Submit/dave/Hash/해시맵디자인/solution.py
- Submit/dave/Stack_Queue/기능개발/solution.py
- Submit/dave/Stack_Queue/다리를_지나는_트럭/solution.py
- Submit/dave/Stack_Queue/주식가격/solution.py
> Hash 2 dave

- Submit/dave/BruteForce/README.md
- Submit/dave/Greedy/README.md
- Submit/dave/Hash/README.md
- Submit/dave/Heap/README.md
- Submit/dave/Sorting/README.md
- Submit/dave/Stack_Queue/README.md
- Submit/dave/Stack_Queue/기능개발/solution.py
- Submit/dave/Stack_Queue/다리를_지나는_트럭/solution.py
- Submit/dave/Stack_Queue/주식가격/solution.py
- Submit/dave/Stack_Queue/프린터/solution.py
문제 "프린터 " 외에 나머지 문제 풀이 PR 보냅니다.
> 1주차 나머지 문제 풀이입니다.

- Submit/kukim/Hash/베스트앨범/solution.py
- Submit/kukim/Hash/상위K빈도요소/solution.py
- Submit/kukim/Hash/위장/solution.py
- Submit/kukim/Hash/전화번호목록/solution.py
- Submit/kukim/Hash/중복문자없는가장긴문자열/solution.py
> [kukim - Hash] : 베스트앨범, 상위 K빈도요소, 위장, 전화번호목록, 중복문자없는가장긴문자열

- Submit/yeha/BruteForce/README.md
- Submit/yeha/Greedy/README.md
- Submit/yeha/Hash/README.md
- Submit/yeha/Hash/전화번호 목록/solution.py
- Submit/yeha/Heap/README.md
- Submit/yeha/Sorting/README.md
- Submit/yeha/Stack_Queue/README.md
- Submit/yeha/Stack_Queue/주식문제/solution.py
- 사용하는 아이디를 바꾸어 1주차 주식가격과 전화번호 목록 함께 PR 보냅니다.
> [yeha] Hash 전화번호 목록 문제 풀이

- Submit/leejaewon/BruteForce/README.md
- Submit/leejaewon/Greedy/README.md
- Submit/leejaewon/Hash/README.md
- Submit/leejaewon/Hash/베스트앨범/solution.py
- Submit/leejaewon/Hash/완주하지못한선수/solution.py
- Submit/leejaewon/Hash/위장/solution.py
- Submit/leejaewon/Hash/전화번호목록/solution.py
- Submit/leejaewon/Hash/중복문자없는가장긴문자열/solution.py
- Submit/leejaewon/Heap/README.md
- Submit/leejaewon/Sorting/README.md
- Submit/leejaewon/Stack_Queue/README.md
- Submit/leejaewon/Stack_Queue/기능개발/solution.py
- Submit/leejaewon/Stack_Queue/다리를지나는트럭/solution.py
- Submit/leejaewon/Stack_Queue/주식가격/solution.py
- Submit/leejaewon/Stack_Queue/프린터/solution.py
* <기능개발> 문제 1차 완료했습니다.
* <프린터> 문제 1차 완료했습니다.
* <다리를 지나는 트럭> 문제 1차 완료했습니다.
* <주식가격> 문제 1차 완료했습니다.
* <완주하지 못한 선수> 문제 1차 완료 했습니다.
* <전화번호 목록> 문제 1차 완료 했습니다.
* <위장> 문제 1차 완료했습니다.
* <베스트앨범> 문제 1차 완료했습니다.
* <중복문자 없는 가장 긴 문자열> 문제 1차 완료했습니다.
> [Review] 1'st Complete part of Hash and Stack_Queue problems

- Submit/leejaewon/BruteForce/README.md
- Submit/leejaewon/Greedy/README.md
- Submit/leejaewon/Hash/README.md
- Submit/leejaewon/Hash/베스트앨범/solution.py
- Submit/leejaewon/Hash/상위K빈도요소/solution.py
- Submit/leejaewon/Hash/완주하지못한선수/solution.py
- Submit/leejaewon/Hash/위장/solution.py
- Submit/leejaewon/Hash/전화번호목록/solution.py
- Submit/leejaewon/Hash/중복문자없는가장긴문자열/solution.py
- Submit/leejaewon/Heap/README.md
- Submit/leejaewon/Sorting/README.md
- Submit/leejaewon/Stack_Queue/README.md
- Submit/leejaewon/Stack_Queue/기능개발/solution.py
- Submit/leejaewon/Stack_Queue/다리를지나는트럭/solution.py
- Submit/leejaewon/Stack_Queue/주식가격/solution.py
- Submit/leejaewon/Stack_Queue/프린터/solution.py
> [Review] 1'st Complete 상위 K빈도 요소 problem

- Submit/leejaewon/BruteForce/README.md
- Submit/leejaewon/Greedy/README.md
- Submit/leejaewon/Hash/README.md
- Submit/leejaewon/Hash/베스트앨범/solution.py
- Submit/leejaewon/Hash/상위K빈도요소/solution.py
- Submit/leejaewon/Hash/완주하지못한선수/solution.py
- Submit/leejaewon/Hash/위장/solution.py
- Submit/leejaewon/Hash/전화번호목록/solution.py
- Submit/leejaewon/Hash/중복문자없는가장긴문자열/solution.py
- Submit/leejaewon/Heap/README.md
- Submit/leejaewon/Sorting/README.md
- Submit/leejaewon/Stack_Queue/README.md
- Submit/leejaewon/Stack_Queue/기능개발/solution.py
- Submit/leejaewon/Stack_Queue/다리를지나는트럭/solution.py
- Submit/leejaewon/Stack_Queue/주식가격/solution.py
- Submit/leejaewon/Stack_Queue/프린터/solution.py
- Submit/leejaewon/Test/추가모의고사1/프로그래밍1/solution.py
- Submit/leejaewon/Test/추가모의고사1/프로그래밍2/solution.py
- Submit/leejaewon/Test/추가모의고사2/프로그래밍1/solution.py
- Submit/leejaewon/Test/추가모의고사2/프로그래밍2/solution.py
* <추가모의고사1-프로그래밍1> 문제 1차 완료했습니다.
* <추가모의고사1-프로그래밍2> 문제 1차 완료했습니다.
* <추가모의고사2-프로그래밍1> 문제 1차 완료했습니다.
* <추가모의고사2-프로그래밍2> 문제 1차 완료했습니다.
> [Review] 1'st Complete 추가모의고사1,2 problems

- Submit/yeha/Test/1-1.py
- Submit/yeha/Test/1-2.py
- Submit/yeha/Test/2-1.py
* 1-1, 1-2, 2-1 문제 업로드하여 PR보냅니다.
> Add 추가 모의고사

- .gitignore
- Submit/leejaewon/BruteForce/모의고사/solution.py
- Submit/leejaewon/BruteForce/소수찾기/solution.py
- Submit/leejaewon/BruteForce/카펫/solution.py
- Submit/leejaewon/Heap/K_Closest_Points_to_Origin/solution.py
- Submit/leejaewon/Heap/Kth_Largest_Element_in_an_Array/solution.py
- Submit/leejaewon/Heap/Reduce_Array Size_to_The_Half/solution.py
- Submit/leejaewon/Heap/디스크컨트롤러/solution.py
- Submit/leejaewon/Heap/이중우선순위큐/solution.py
* <모의고사> 문제 1차 완료했습니다.
* <소수찾기> 문제 1차 완료했습니다.
* <카펫> 문제 1차 완료했습니다.
> [Review] 1'st Complete 모의고사, 소수찾기, 카펫 problem

- Submit/leejaewon/Heap/K_Closest_Points_to_Origin/solution.py
- Submit/leejaewon/Heap/Kth_Largest_Element_in_an_Array/solution.py
- Submit/leejaewon/Heap/Reduce_Array Size_to_The_Half/solution.py
- Submit/leejaewon/Heap/디스크컨트롤러/solution.py
- Submit/leejaewon/Heap/이중우선순위큐/solution.py
* <배열의 K번째 큰 요소> 문제 1차 완료했습니다.
* <디스크 컨트롤러> 문제 1차 완료했습니다.
* <이중우선순위큐> 문제 1차 완료했습니다.
* <K Closest Points to Origin> 문제 1차 완료했습니다.
* <Reduce Array Size to The Half> 문제 1차 완료했습니다.
> [Review] Completed the heap chapter this week 

- Submit/sehee/스타트와 링크(백준)/스타트와 링크.py
조합과 구현으로 풀었음 -> 입력값의 크기가 작았기 때문
내 풀이) deque로 풀 시 개수가 전부 달라서 해결하기 못함
정답) 무조건 짝수니까는 문자길이를 반으로 잘라서 돌면 됨
> 스타트와 링크 완료

- Submit/dave/BruteForce/블랙잭/solution.py
- Submit/dave/BruteForce/소수찾기/solution.py
- Submit/dave/BruteForce/스타트와링크/solution.py
- Submit/dave/BruteForce/좋은수열/solution.py
- Submit/dave/BruteForce/치킨배달/solution.py
> 5회차 완전탐색 문제풀이 완료

- Submit/leejaewon/BruteForce/블랙잭/solution.py
- Submit/leejaewon/BruteForce/차이를최대로/solution.py
> [Review] 1'st Complete 블랙잭 problem

- Submit/leejaewon/BruteForce/차이를최대로/solution.py
> [Review] 1'st Complete 차이를 최대로 problem

- Submit/dave/Sorting/H-Index/solution.py
- Submit/dave/Sorting/InsertionSortList/solution.py
- Submit/dave/Sorting/MergeIntervals/solution.py
- Submit/dave/Sorting/SortList/solution.py
> 6회차 정렬 문제풀이 완료

- Submit/dave/Greedy/섬_연결하기/solution.py
- Submit/dave/Greedy/주식을사고팔기가장좋은시점2/solution.py
- Submit/dave/Greedy/주유소/solution.py
7회차 그리디 문제 풀이
- 섬 연결하기
- 주식을 사고 팔기 가장 좋은 시점
- 주유소
> Greedy dave 1

- Submit/leejaewon/BruteForce/스타트와링크/solution.py
> [Review] 1'st Commit 스타트와링크 problem

- Submit/yeha/DP/이친수/solution.py
> [yeha] DP 이친수 풀이

- Submit/kukim/DP/1로만들기.py
- Submit/kukim/DP/동전1.py
- Submit/kukim/DP/동전2.py
- Submit/kukim/DP/이동하기.py
- Submit/kukim/DP/이친수.py
> kukim : DP 5문제풀이
